### PR TITLE
Added test for cam2image and showimage

### PR DESCRIPTION
**Pull request by esteve**
Connects to #43

### CODE REVIEW

**Comment by esteve** [comment]
CI jobs:

http://ci.ros2.org/job/ci_linux/684/
http://ci.ros2.org/job/ci_osx/560/
http://ci.ros2.org/job/ci_windows_connext_dynamic/34/
http://ci.ros2.org/job/ci_windows_connext_static/34/
http://ci.ros2.org/job/ci_windows_opensplice/752/

**Comment by esteve** [comment]
The added mp4 file is this one, the license should be fine.

https://archive.org/details/SaucersInTheSky_521

**Comment by dirk-thomas** [comment]
Please don't add a 9 MB test file to the repo but download it from somewhere.

**Comment by esteve** [comment]
@dirk-thomas I considered that, but ended up opting for having the test fixtures bundled with the tests, because I like tests that are more or less self contained and because I think there's is value in distributing the whole test. I can see advantages for both approaches (include the test resources or fetching them from a remote location). Thoughts? @codebot @gerkey @jacquelinekay @tfoote @wjwwood

**Comment by wjwwood** [comment]
:-1: :cookie: for including binary files in the repository, as they persist in the history for ever making the repository huge. I'd prefer downloading the video file. Does the content of the video matter? You could instead generate a movie file using OpenCV fairly easily.

**Comment by wjwwood** [comment]
:meat_on_bone: It depends on how you're testing it, I guess it helps because the size of the image changes, but it's not clear to me how we're asserting that the image is displayed in the GUI correctly. It would be useful for acceptance testing but not necessarily automated testing.

**Comment by tfoote** [comment]
Try [github LFS](https://github.com/blog/1986-announcing-git-large-file-storage-lfs) otherwise we can fallback to new cmake download tools from download.ros.org

**Comment by esteve** [comment]
I've tried Git LFS and seems to work, I've triggered a Linux CI job, let's see if this works on the buildfarm:

http://ci.ros2.org/job/ci_linux/688/

:ice_cream:

**Comment by esteve** [comment]
The LFS client needs to be installed on the slaves, I'm going to try adding it to the Docker bootstrap script for Linux and install the client manually on Windows and OSX.

**Comment by dirk-thomas** [comment]
Since we also need to support other VCS should we just go for a download solution and not do any extra stuff for LFS?

**Comment by esteve** [comment]
I'd rather use LFS since it's very well integrated into GitHub.

**Comment by wjwwood** [comment]
> Since we also need to support other VCS should we just go for a download solution and not do any extra stuff for LFS?

Why do we need to support other VCS? And how does that impact the decision to use LFS here?

**Comment by dirk-thomas** [comment]
If we want ROS users to be able to store their code in non-git repos and also have tests requiring large data we need to provide a mechanism to download these data. If we have the infrastructure anyway I don't see a reason to spend extra effort on this special solution.

**Comment by gerkey** [comment]
As we discussed in today's meeting, we're going to try LFS here and see how it works.  That does not stop us from trying other options later.

**Comment by wjwwood** [comment]
I thought the idea is that there is no extra effort? Looks to me that it is a "symlink" file and that you just need to run a command after checkout like initializing submodules. It shouldn't require any extra infrastructure on our part, unless I'm missing something.

Also I thought that CMake provides download infrastructure and we don't need to? So we're not do this instead of spending time on new infrastructure that others would use.

**Comment by esteve** [comment]
@wjwwood you just need to install `git-lfs` and run `git lfs install` only once to. After that, it's all transparent and any checkout will retrieve the files that are tracked via LFS.

**Comment by esteve** [comment]
The Linux CI job passes:

http://ci.ros2.org/job/ci_linux/690/

unfortunately Windows and OSX don't, git-lfs is properly installed and working (I see the 9 MB .mp4 file in the workspace), but the tests don't pass. I'll look into it a bit more, maybe the tests need more work.

**Comment by wjwwood** [comment]
@esteve The OS X job is downloading the file near as I can tell:

From http://ci.ros2.org/job/ci_osx/570/consoleFull:
```
03:12:01 === ./src/ros2/demos (git) ===
03:12:01 Downloading image_tools/test/test_capture.mp4 (9.13 MB)
03:12:01 Switched to a new branch 'image_tools_tests'
03:12:01 Branch image_tools_tests set up to track remote branch image_tools_tests from origin.
```

**Comment by tfoote** [comment]
@wjwwood will look and see if this is still needed.

**Comment by wjwwood** [comment]
@codebot 🍔

**Pull request closed without merging**
