### PR TITLE
Filter qos overrides in paramter events demos

### PR DESCRIPTION
**Pull request by ivanpauno**
Fixes https://github.com/ros2/demos/issues/490.

I did this because it was easier than fixing the text expectations, but doing the opposite might make more sense.

### CODE REVIEW

**Comment by ivanpauno** [comment]
I'm not sure why the PR checker is failing, but it's not related to this PR.

**Comment by mjcarroll** [comment]
Running CI with Connext:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13948/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8785/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11651/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14033/)

**Comment by ivanpauno** [comment]
CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13951/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8788/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11654/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14036/)

**Review by mjcarroll — APPROVED** [review]
LGTM, arm64 is expected due to lack of connext there?

**Comment by mjcarroll** [comment]
The `Rpr` failure seems to be `cyclonedds` related, so nothing to do with this PR

```
RuntimeError: Failed to initialize init_options: failed to load shared library 'librmw_cyclonedds_cpp.so' due to dlopen error: librmw_cyclonedds_cpp.so: cannot open shared object file: No such file or directory, at /tmp/binarydeb/ros-rolling-rcutils-3.1.0/src/shared_library.c:97, at /tmp/binarydeb/ros-rolling-rmw-implementation-2.2.0/src/functions.cpp:74, at /tmp/binarydeb/ros-rolling-rcl-2.5.2/src/rcl/init_options.c:75
```

**Pull request merged**
