### PR TITLE
Use raw data directly

### PR DESCRIPTION
**Pull request by esteve**
Fix compiler warning

Connects to ros2/ros2#53

### CODE REVIEW

**Comment by esteve** [comment]
CI job:

http://ci.ros2.org/job/ros2_batch_ci_windows/210/

**Comment by dirk-thomas** [comment]
What happened to the previous patch which did exactly this a week ago??? 38e89cd6b4c8e01284d33ba4eea11c66b8138721

**Comment by esteve** [comment]
@dirk-thomas I don't know, I found it weird because I remembered I already pushed this change, but I just thought it was my faulty memory. Anyway, I just checked the changelog for master and it's not there.

**Comment by dirk-thomas** [comment]
The dashboard history does only show information for the last four days which does not include who force pushed to master.

+1 anyway again to fix the memory leak.

**Pull request merged**
