### PR TITLE
Fix topic_monitor for high publication rate

### PR DESCRIPTION
**Pull request by eliasdc**
See #460 for explanation.

### CODE REVIEW

**Comment by ivanpauno** [comment]
@cottsay friendly ping

**Comment by cottsay** [comment]
I'm going to try to take a look at this next week. Sorry it's taking so long...

**Comment by mjeronimo** [comment]
@cottsay 

FYI - I tried this PR since I found this issue also. I pulled the branch, rebased (C++17 changes required). and ran the following:

ros2 launch topic_monitor fragmentation_demo.launch.py

The CPU utilization was about 10% on my system with the fix versus about 100% without. Looks good to me.

**Review by mjeronimo — APPROVED** [review]

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14600/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9355/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12266/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14734/)

**Pull request merged**
