### PR TITLE
comply with namespaces

### PR DESCRIPTION
**Pull request by Karsten1987**
connects to ros2/rcl#127

### CODE REVIEW

**Comment by dirk-thomas** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/2717/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/260/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/2182/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/2849/)

**Comment by mikaelarguedas** [comment]
thanks @dirk-thomas for launching CI on this

**Comment by dirk-thomas** [comment]
This looks good. @ros2/team Should we merge this without @Karsten1987?

**Comment by mikaelarguedas** [comment]
sounds good to me the change is a day old and passes CI :+1:

**Comment by dirk-thomas** [comment]
@Karsten1987 just said via text that this depends on one of the other pending PRs. So I won't merge this but leave it up to him.

**Comment by Karsten1987** [comment]
I can't access github, but I can reply via email from the plane. This 21th
century is so amazing.

This demo needs the rcl_lifecycle PR to be merged. There is a
rcutils_allocator branch for rcl which changes the topics from having
double underscores to a forward slash. I won't have proper access before
the 14th.
I could though trigger a new set of CI jobs for this branch, so that if
this is good to go, we can merge the demo code.
Can somebody link the CI jobs here?

**Pull request merged**
