### PR TITLE
add talker_listener.launch.py new-style launch file

### PR DESCRIPTION
**Pull request by wjwwood**
Connects to ros2/launch#76

### CODE REVIEW

**Comment by wjwwood** [comment]
I'd like to expand this to include launch files for everything, but after we get to review.

**Comment by wjwwood** [comment]
I expanded the launch files to include all the topics and service demos in `demo_nodes_cpp`. If anyone has time to review these quickly, I'd appreciate it!

**Comment by dirk-thomas** [comment]
Should the launch files have the executable bit set?

**Comment by dirk-thomas** [comment]
Nvm - the can't be invoked in their own... Ignore the noise.

**Comment by wjwwood** [comment]
I'll look into the hang.

**Comment by dhood** [comment]
think this should add a dependency on `launch_ros` in the package.xml yeah?

**Comment by wjwwood** [comment]
> think this should add a dependency on launch_ros in the package.xml yeah?

Not sure, I guess you could, but a similar thing comes up where you wonder if every package in ROS 1 that has a launch file should depend on `roslaunch`.

If we decide to add a dependency, then we might as well add `ros2launch` in addition to (or instead of) `launch_ros`. Because those launch files cannot be run on their own.

**Comment by dhood** [comment]
I think adding a `ros2launch` dependency is a step further than necessary, because even though they're not usable on their own, it doesn't have to be `ros2launch` that uses them (could theoretically be anyone).

But I take your point about having all ROS 1 packages depend on roslaunch. In that sense I think it's reasonable that only packages that are actually launching launch files (e.g. in tests) depend on `launch_ros` themselves.

**Comment by dirk-thomas** [comment]
Since the launch files do import `launch_ros` I think the packages should have an `exec_depend` on `launch_ros`.

Regarding the dependency on `ros2launch`: while I can see the convenience if someone would only install that package how it would help I wouldn't add it since `ros2launch` is just one way these launch files can be used. As an analogy: if a package provides a component (a node compiled into a shared library) I wouldn't expect a dependency on something like `ros2run-component` (not that we have that - just as an example).

**Comment by wjwwood** [comment]
https://github.com/ros2/launch/issues/80

**Pull request merged**
