### PR TITLE
Revert "Add type masquerading demos"

### PR DESCRIPTION
**Pull request by wjwwood**
Reverts ros2/demos#482

Fixes #520.

### CODE REVIEW

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14648/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9401/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12312/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14792/)

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
I'm going to go ahead and merge this one to unblock CI.

**Comment by jasonbeach** [comment]
What was the issue (why was this reverted)?

**Comment by clalancette** [comment]
> What was the issue (why was this reverted)?

At the time it broke CI, but we have had this back in the code (via #521) since May of 2021.

**Pull request merged**
