### PR TITLE
fix readme for topic_monitor.

### PR DESCRIPTION
**Pull request by fujitatomoya**
only doc update, part of https://github.com/osrf/ros2_test_cases/issues/904

### CODE REVIEW

**Comment by fujitatomoya** [comment]
@Yadunund please take a look, just a minor doc fix.

**Review by Yadunund — APPROVED** [review]
Thanks for fixing this!

**Comment by fujitatomoya** [comment]
since this is just doc change, we do not need to run CI. i will go ahead to merge this.

**Comment by fujitatomoya** [comment]
@Mergifyio backport iron

**Pull request merged**
