### PR TITLE
fix generating unique files on Windows

### PR DESCRIPTION
**Pull request by dirk-thomas**
Fix regression from #67 on Windows.

Before: http://ci.ros2.org/job/ci_windows/2118/
After: http://ci.ros2.org/job/ci_windows/2119/

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The keywords are "CMake generator expressions": https://cmake.org/cmake/help/v3.5/manual/cmake-generator-expressions.7.html

**Comment by dirk-thomas** [comment]
Good point. I changed it to `<CONFIG>`. If http://ci.ros2.org/job/ci_windows/2120/ passes I will merge this.

**Comment by wjwwood** [comment]
Thanks.

**Comment by dirk-thomas** [comment]
I have updated the existing code base to use `<CONFIG>` instead of `<CONFIGURATION>`:

* https://github.com/ros2/demos/commit/f0e85179ab3aaf8ead3b257f851089022c49d8b7
* https://github.com/ros2/rcl/commit/d681d29219c41708562591a378585cd02f29b559
* https://github.com/ros2/rclcpp/commit/0515e7aaf2a1e279c2f78c6a5d689d2778964c98
* https://github.com/ros2/ros1_bridge/commit/25d0f4f68e00f149c18cd6345a22867414cec0e8
* https://github.com/ros2/rosidl/commit/cd4a1e753719f682ab559cfd533043ca17d47e0e
* https://github.com/ros2/system_tests/commit/481735a9c3edf618af763fe8bc3805bc1a12af29
* https://github.com/ros2/tutorials/commit/e265f7991d4d35c4e41c77abcb55d33c741c8209

**Pull request merged**
