### PR TITLE
Fix std::sin call

### PR DESCRIPTION
**Pull request by Theosakamg**
issue #124 

connects to #124

### CODE REVIEW

**Comment by wjwwood** [comment]
I changed it to use the c++ version of the include, here's CI:

- Linux:
  - [Build Status](http://ci.ros2.org/job/ci_linux/2425/)
- Linux-aarch64:
  - [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/56/)
- macOS:
  - [Build Status](http://ci.ros2.org/job/ci_osx/1878/)
- Windows:
  - [Build Status](http://ci.ros2.org/job/ci_windows/2549/)

**Comment by Theosakamg** [comment]
👍

**Comment by Karsten1987** [comment]
The test failures are unrelated, right? If so, I'd +1 this.

**Comment by wjwwood** [comment]
Yeah, I only ran ci to make sure there was no compiler warning on windows.

**Comment by wjwwood** [comment]
Thanks @Theosakamg!

**Pull request merged**
