### PR TITLE
Add a demo for the new ParameterEventHandler class

### PR DESCRIPTION
**Pull request by mjeronimo**
This demo depends on the following functionality: ros2/rclcpp#829, which must be integrated before this PR.

Signed-off-by: Michael Jeronimo michael.jeronimo@openrobotics.org

### CODE REVIEW

**Comment by mjeronimo** [comment]
@ros-pull-request-builder retest this please

**Comment by mjeronimo** [comment]
@ros-pull-request-builder retest this please

**Comment by mjeronimo** [comment]
@ros-pull-request-builder retest this please

**Review by jacobperron — APPROVED** [review]
LGTM

**Comment by mjeronimo** [comment]
@ros-pull-request-builder retest this please

**Comment by mjeronimo** [comment]
@ros-pull-request-builder retest this please

**Comment by mjeronimo** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14054/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8875/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11747/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14145/)

**Comment by mjeronimo** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14063/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8883/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11755/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14154/)

**Comment by mjeronimo** [comment]
Merging since the CI is passing and the PR builder issues were there previously (see https://build.ros2.org/view/Rdev/job/Rdev__demos__ubuntu_focal_amd64/28/).

**Pull request merged**
