### PR TITLE
Add type masquerading demos

### PR DESCRIPTION
**Pull request by audrow**
This PR shows how type masquerading could be for images and with an intraprocess pub/sub.

Currently, type masquerading isn't implemented.

<hr>

This is part of the Type Masquerading project.

### CODE REVIEW

**Review by wjwwood — APPROVED** [review]
lgtm, will wait for @audrow to review and run CI.

**Review by audrow — COMMENTED** [review]
I can't approve this PR because I opened the PR. 

These changes look good to me with green CI.
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14628/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9383/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12294/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14771/)

**Review by wjwwood — APPROVED** [review]

**Comment by wjwwood** [comment]
Looks like we'll have to investigate the opencv related failure.

**Comment by wjwwood** [comment]
I opened https://github.com/ros2/rclcpp/pull/1674 to address the GCC issue. @audrow can you run CI? I know you did something odd to run it before, IIRC.

**Comment by audrow** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14641/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9394/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12305/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14785/)

**Comment by audrow** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14644/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9397/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12308/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14788/)

**Review by wjwwood — APPROVED** [review]

**Pull request merged**
