### PR TITLE
Update intra_process_demo for OpenCV 4 compatibility

### PR DESCRIPTION
**Pull request by jacobperron**
Follow up from #306. Forget to update the intra_proces_demo package...

### CODE REVIEW

**Comment by jacobperron** [comment]
Build with OpenCV4 to be sure there's nothing else missing: [Build Status](https://ci.ros2.org/job/test_ci_osx/132/)

**Comment by nuclearsandwich** [comment]
Xenial [Build Status](https://ci.ros2.org/job/ci_linux/6025/)

**Comment by jacobperron** [comment]
CI up to intra_process_demo:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/6032/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2530/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4975/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5904/)

**Comment by nuclearsandwich** [comment]
Xenial (which is using OpenCV from upstream 2.4.9) appears to be missing some of the newly used API.

**Comment by jacobperron** [comment]
> Xenial (which is using OpenCV from upstream 2.4.9) appears to be missing some of the newly used API.

@nuclearsandwich @wjwwood Thoughts on adding pre-processor checks? Specifically needed in three different places:

```diff
image_tools/src/burger.cpp
@@ -82,7 +82,11 @@ Burger::Burger()
   std::vector<uint8_t> burger_png;
   burger_png.resize(burger_size);
   decode_base64(BURGER, burger_png);
+#if CV_MAJOR_VERSION < 3
+  burger_template = cv::imdecode(burger_png, CV_LOAD_IMAGE_COLOR);
+#else
   burger_template = cv::imdecode(burger_png, cv::ImreadModes::IMREAD_COLOR);
+#endif
   cv::floodFill(burger_template, cv::Point(1, 1), CV_RGB(1, 1, 1));
   cv::compare(burger_template, 1, burger_mask, cv::CMP_NE);
 #ifndef _WIN32

image_tools/src/cam2image.cpp
@@ -156,8 +156,13 @@ int main(int argc, char * argv[])
     cap.open(0);
 
     // Set the width and height based on command line arguments.
+#if CV_MAJOR_VERSION < 3
+    cap.set(CV_CAP_PROP_FRAME_WIDTH, static_cast<double>(width));
+    cap.set(CV_CAP_PROP_FRAME_HEIGHT, static_cast<double>(height));
+#else
     cap.set(cv::CAP_PROP_FRAME_WIDTH, static_cast<double>(width));
     cap.set(cv::CAP_PROP_FRAME_HEIGHT, static_cast<double>(height));
+#endif
     if (!cap.isOpened()) {
       RCLCPP_ERROR(node_logger, "Could not open video stream");
       return 1;

intra_process_demo/include/image_pipeline/camera_node.hpp
@@ -38,8 +38,13 @@ public:
   {
     // Initialize OpenCV
     cap_.open(device);
+#if CV_MAJOR_VERSION < 3
+    cap_.set(CV_CAP_PROP_FRAME_WIDTH, static_cast<double>(width));
+    cap_.set(CV_CAP_PROP_FRAME_HEIGHT, static_cast<double>(height));
+#else
     cap_.set(cv::CAP_PROP_FRAME_WIDTH, static_cast<double>(width));
     cap_.set(cv::CAP_PROP_FRAME_HEIGHT, static_cast<double>(height));
+#endif
     if (!cap_.isOpened()) {
       throw std::runtime_error("Could not open video stream!");
     }
```

**Comment by wjwwood** [comment]
That's unfortunate, but perhaps the best thing we can do for now. We can have a TODO/issue to remove that when we drop support for Xenial.

When are we doing that btw, isn't the case for Dashing?

**Comment by jacobperron** [comment]
I'm not sure what the timeline is, but if we're dropping Xenial support in Dashing then is it an option to create a `crystal-devel` branch that doesn't have these OpenCV updates?

**Comment by nuclearsandwich** [comment]
> When are we doing that btw, isn't the case for Dashing?

I think the plan is to pitch dropping Xenial for Dashing to the technical steering committee at the next meeting.

**Comment by nuclearsandwich** [comment]
> if we're dropping Xenial support in Dashing then is it an option to create a `crystal-devel` branch that doesn't have these OpenCV updates?

I don't think that gains us much because we're trying to support Xenial with OpenCV 2 and MacOS with OpenCV4 within Crystal. so whether we add this logic to master or create a separate Crystal branch doesn't obviate the need for it, and since we haven't disabled Xenial jobs yet (and Xenial may remain supported Dashing possibly) omitting the logic on master would break the Xenial jobs while that all shakes out.

**Comment by jacobperron** [comment]
Bionic: [Build Status](https://ci.ros2.org/job/ci_linux/6035/)
Xenial: [Build Status](https://ci.ros2.org/job/ci_linux/6034/)

**Comment by jacobperron** [comment]
Test failures appear irrelevant to this PR.

**Comment by nuclearsandwich** [comment]
> The test failures on Xenial appear irrelevant to this PR.

The pyqt issue has been long outstanding. I haven't seen [this tlsf failure](https://ci.ros2.org/job/ci_linux/6034/testReport/junit/tlsf_cpp/AllocatorTest__rmw_connext_cpp/allocator_unique_ptr/) before in recent builds.

**Comment by jacobperron** [comment]
I can reproduce the tlsf failure without this change. New issue opened: ros2/realtime_support#69

**Pull request merged**
