### PR TITLE
use the sensor data profile

### PR DESCRIPTION
**Pull request by wjwwood**
This is a workaround for this: https://github.com/ros2/demos/pull/21#issuecomment-136486901

### CODE REVIEW

**Comment by tfoote** [comment]
+1

**Comment by esteve** [comment]
+1

**Comment by wjwwood** [comment]
I've also added to this pr some fixes for problems running on Windows.

**Comment by esteve** [comment]
+1 to OpenCV changes too.

**Comment by wjwwood** [comment]
CI:

- http://ci.ros2.org/job/ros2_batch_ci_linux/300/
- http://ci.ros2.org/job/ros2_batch_ci_osx/230/
- http://ci.ros2.org/job/ros2_batch_ci_windows/314/

**Comment by tfoote** [comment]
+1

**Comment by wjwwood** [comment]
I'm sure what this test failure is about:

http://ci.ros2.org/job/ros2_batch_ci_osx/230/testReport/junit/(root)/test_non_primary_return_code/test_non_primary_return_code/

But the others are thought to be flaky or are expected (inter-vendor on Windows).

**Pull request merged**
