### PR TITLE
Add rclpy lifecycle demo

### PR DESCRIPTION
**Pull request by ivanpauno**
Demo for https://github.com/ros2/rclpy/pull/865.

### CODE REVIEW

**Review by audrow — APPROVED** [review]
Looks good to me. I like that you added tests.

**Comment by ivanpauno** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15844/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10521/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/13509/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16136/)

**Comment by ivanpauno** [comment]
@ros-pull-request-builder retest this please

**Comment by ivanpauno** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15877/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10554/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/13543/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16180/)

**Pull request merged**
