### PR TITLE
Break line after paren in multiline function calls

### PR DESCRIPTION
**Pull request by rotu**
as per https://github.com/ament/ament_lint/pull/148

Signed-off-by: Dan Rose <dan@digilabs.io>

### CODE REVIEW

**Comment by sloretz** [comment]
CI (testing composition demo_nodes_cpp image_tools pendulum_control lifecycle quality_of_service_demo)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/7603/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3726/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6219/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7425/)

**Comment by rotu** [comment]
@sloretz I don't understand why all these tests are timing out. I don't think it was from my changes. Any insight?

**Comment by jacobperron** [comment]
> I don't understand why all these tests are timing out. I don't think it was from my changes. Any insight?

I believe those timeouts were introduced by https://github.com/ros2/launch/pull/265 (which has since been reverted).

Let's try again:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/7630/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3745/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6238/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7477/)

**Comment by nuclearsandwich** [comment]
@rotu could you please rebase this PR.

**Comment by rotu** [comment]
@nuclearsandwich Done.

**Comment by nuclearsandwich** [comment]
One last CI for luck.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/7899/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3948/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6442/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7764/)

**Comment by nuclearsandwich** [comment]
@rotu am I correct in expecting that we want to merge this before https://github.com/ament/ament_lint/pull/148 ?

**Comment by rotu** [comment]
@nuclearsandwich, yes, so that CI doesn't break when we merge https://github.com/ament/ament_lint/pull/148. I think it makes more sense to do it in the opposite order, so CI enforces correctness of this PR, but @dirk-thomas insisted on fixing the code before we fix the linter.

**Comment by nuclearsandwich** [comment]
> I think it makes more sense to do it in the opposite order, so CI enforces correctness of this PR,

I understand the logic of that workflow. But given that our team wasn't so highly parallelized it doesn't make sense to break builds for the duration of a CI run. It's also possible to verify that the change resolves failures by triggering a CI run that includes https://github.com/ament/ament_lint/pull/148 but not this change and then running the two together without affecting mainline CI for everyone else.

**Comment by rotu** [comment]
That makes even more sense, and I didn't realize it was a possibility. How do I trigger or request such a CI build?

**Comment by nuclearsandwich** [comment]
> That makes even more sense, and I didn't realize it was a possibility. How do I trigger or request such a CI build?

The easiest thing to do is request CI on that ament_lint PR before this merges, then a second round after this does.

**Pull request closed without merging**
