### PR TITLE
Replacing old-style C++ allocator with a polymorphic memory resource (PMR)

### PR DESCRIPTION
**Pull request by AliAshkaniNia**
This is a basic example mimicking the original demo. We could use a more advanced resource, like `unsynchronized_pool_resource`, for a realistic scenario.

### CODE REVIEW

**Comment by AliAshkaniNia** [comment]
This is a change for issue #650  .

**Review by fujitatomoya — CHANGES_REQUESTED** [review]
some uncrustify errors, https://build.ros2.org/job/Rpr__demos__ubuntu_jammy_amd64/235/testReport/junit/demo_nodes_cpp/uncrustify/src_topics_allocator_tutorial_cpp/

and, could you also address DCO error?

**Comment by AliAshkaniNia** [comment]
My apologies, I should have read the ROS2 developer guides before making changes. Now, it is compliant with ROS2 style, and I have also reordered the `#include` statements.

**Review by fujitatomoya — APPROVED** [review]
> We could use a more advanced resource, like unsynchronized_pool_resource, for a realistic scenario.

I am not sure about this, we could. but we would not want to introduce the polymorphic memory details here, instead we would like it to be simple for demonstration code.

**Comment by clalancette** [comment]
> I am not sure about this, we could. but we would not want to introduce the polymorphic memory details here, instead we would like it to be simple for demonstration code.

Yeah, I agree.  What we have here is easy to understand, and is the main point of this tutorial, so I think we should keep it simple.

**Review by clalancette — APPROVED** [review]
Thanks, this is much easier to understand.

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19647/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14155/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/20371/)

**Comment by AliAshkaniNia** [comment]
> Thanks, this is much easier to understand.

Glad I could assist!

**Comment by AliAshkaniNia** [comment]
For the `unsynchronized_pool_resource` stuff, I agree with you. I'm a fan of making tutorials dead simple, which is why I came up with this refactoring idea. Please correct me if I'm wrong, but on the other hand, my perception is that ROS2 comes with "*batteries included*"; it provides all the necessary tools and resources for creating production-ready code. I believe there's a good chance that someone interested in custom allocators might also be interested in using stack memory instead of heap. So, I thought it's worth mentioning that topic thanks to the intuitive API:
```C++
std::array<std::uint8_t, 10*1024> buffer{};
std::pmr::monotonic_buffer_resource upstream_resource(buffer.data(), buffer.size());
std::pmr::unsynchronized_pool_resource mem_resource(&upstream_resource);

auto alloc = std::make_shared<Alloc>(&mem_resource);
```

Again, this is just a suggestion, and overall, I agree that it might be too complicated for the tutorial. I just mentioned it for the sake of completeness.

**Pull request merged**
