### PR TITLE
Migrate std::bind calls to lambda expressions

### PR DESCRIPTION
**Pull request by FelipeGdM**
This PR is a follow up from the work done in the documentation https://github.com/ros2/ros2_documentation/pull/4041

This PR migrates the C++ examples that use std::bind to equivalent lambda expression code

### CODE REVIEW

**Review by fujitatomoya — APPROVED** [review]

**Comment by fujitatomoya** [comment]
@tylerjw could you do another review for this?

@FelipeGdM after this PR is merged, we can get back to https://github.com/ros2/ros2_documentation/pull/4041 to make sure if everything aligns with this PR.

**Comment by clalancette** [comment]
@tylerjw to review

**Review by tylerjw — APPROVED** [review]
This looks good, thank you!

**Comment by sloretz** [comment]
CI ([repos](https://gist.githubusercontent.com/sloretz/18e8966f46d81fa12223a30cdc2d128f/raw/afbc1759de82cf2baf6411a0e53414632ebfc300/ros2.repos) build: `--packages-up-to action_tutorials_cpp composition image_tools intra_process_demo lifecycle logging_demo` test: `--packages-select action_tutorials_cpp composition image_tools intra_process_demo lifecycle logging_demo`)

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20008/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14472/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/20718/)

**Pull request merged**
