### PR TITLE
remove workaround as connext declares dep on libdl now

### PR DESCRIPTION
**Pull request by mikaelarguedas**
connects to ros2/rmw_connext#275

### CODE REVIEW

**Comment by dhood** [comment]
I think this was added specifically for the linktime_composition part of the demo (I imagine otherwise the linker would not bother to link against the various components because they are not coded dependencies in `linktime_composition.cpp`). I don't think it's related to the connext workaround (which was probably redundant by the time this demo was created)

**Comment by mikaelarguedas** [comment]
Thanks for the feedback, yeah that was my guess too and wanted to confirm it would fail without it. As usual this is not ready for review until being placed in the review column.

**Comment by dhood** [comment]
Personally I appreciate input from others as soon as possible if it looks like I'm going in the wrong direction with something, so I figured I'd point it out even if the PR is labelled as "in progress", didn't mean to step on your toes :smile:

**Comment by mikaelarguedas** [comment]
Yeah I understood your intent that's why I thanked the feedback. I'll make it clearer in the future when I'm confirming the need for extra logic and not expecting reviews on it :wink: .

**Pull request closed without merging**
