### PR TITLE
update launch file names to match recommended format

### PR DESCRIPTION
**Pull request by patrickwasp**
companion pull request for https://github.com/ros2/ros2_documentation/pull/3166

### CODE REVIEW

**Review by fujitatomoya — APPROVED** [review]

**Comment by fujitatomoya** [comment]
@patrickwasp can you address DCO?

**Comment by patrickwasp** [comment]
@fujitatomoya DCO fixed

**Review by audrow — APPROVED** [review]
Looks good to me with green CI.

**Review by fujitatomoya — APPROVED** [review]

**Comment by fujitatomoya** [comment]
@audrow can you take care of this? i do not have write permission to this repository.

**Comment by clalancette** [comment]
Sorry for the delay here.  I've now rebased this and fixed a few other things that have changed in the meantime.  I'm going to approve and run CI on it next.

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18195/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12728/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18855/)

**Pull request merged**
