### PR TITLE
Remove action_tutorials_interfaces.

### LINKED ISSUE #702: code line does not match the official tutorial
with the Fibonacci.action file defined in [official action tutorial](https://docs.ros.org/en/humble/Tutorials/Intermediate/Creating-an-Action.html#defining-an-action) as: 

```
# Request
---
# Result
---
# Feedback
```

Code here should be modified to `auto & sequence = feedback->partial_sequence;`, otherwise it cannot be compiled successfully

https://github.com/ros2/examples/blob/8a9fbfb54ffb600728644f2f310a8f4b1e23d5b6/rclcpp/actions/minimal_action_server/member_functions.cpp#L76

### PR DESCRIPTION
**Pull request by clalancette**
We have this message duplicated three times in the core; once in here, once in example_interfaces, and once in test_interface_files.  That seems a bit excessive, so remove this third copy and make the action_tutorials use the example_interfaces version of Fibonacci.action instead.

This change obviously changes the dependencies of the action_tutorials_cpp and action_tutorials_py packages, in that it removes action_tutorials_interfaces and adds in example_interfaces.  I believe that this should be fine from an inter-repository standpoint, as the demos repository already contains other packages (composition, quality_of_service_demo_cpp, demo_nodes_py, demo_nodes_cpp) that depend on example_interfaces.

This will fix #702  by at least removing one of our duplicate copies of this message.

### CODE REVIEW

**Comment by clalancette** [comment]
Pulls: ros2/demos#701
Gist: https://gist.githubusercontent.com/clalancette/f40892f15019e2125c75b9041490e888/raw/9eee2c252a0399a1fc03246677ea5fcd590e76fd/ros2.repos
BUILD args:  --packages-above-and-dependencies action_tutorials_py action_tutorials_cpp
TEST args:  --packages-above action_tutorials_py action_tutorials_cpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14488
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21761/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16034/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1265/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22461/)

**Review by fujitatomoya — APPROVED** [review]
so the expectation is that nobody in the downstream depends on this `action-tutorials-interfaces`, i believe that should be fine.

lgtm with green CI.

**Comment by clalancette** [comment]
> so the expectation is that nobody in the downstream depends on this `action-tutorials-interfaces`, i believe that should be fine.

Actually, this is a great question, and one I should have considered.

I took a look at all of the packages currently released into Rolling, and besides `action_tutorials_py` and `action_tutorials_cpp` (fixed here), the following depend on `action_tutorials_interfaces`:

* https://github.com/ros2/variants/blob/70f5a409ae7a9baa44950bf8468742256de67c43/desktop/package.xml#L29
* https://github.com/DLu/simple_actions/blob/aa5134f142558bd0f6a16c4760fcb13841867470/package.xml#L16
* https://github.com/ros-teleop/teleop_tools/blob/b40c474408a0d449495d3922d06e5fa67bd24da7/joy_teleop/package.xml#L20

I'll follow up with those projects to remove their use of `action_tutorials_interfaces` before we merge this in.

**Comment by ahcorde** [comment]
PRs created
 - teleop_tools https://github.com/ros-teleop/teleop_tools/pull/88
 - ROS 2 variants https://github.com/ros2/variants/pull/44
 - simple_actions https://github.com/DLu/simple_actions/pull/13

**Comment by clalancette** [comment]
I'm going to go ahead and merge this one in.  That will break `simple_actions` for now, but it should be easy enough to fix it later on just by merging the above PR.  Thanks @ahcorde for the extra work here!

**Pull request merged**
