### PR TITLE
Remove ineffective log output (#450)

### PR DESCRIPTION
**Pull request by y-okumura-isp**
Signed-off-by: y-okumura-isp <y-okumura@isp.co.jp>

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
Seems reasonable to me.  @y-okumura-isp Out of curiosity, what caused you to look at this?  That is, what problem did you run into?

In any case, I'll run CI on this next.

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13323/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8253/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11054/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13370/)

**Comment by y-okumura-isp** [comment]
@clalancette Thank you for review.

> Out of curiosity, what caused you to look at this? That is, what problem did you run into?

We have interests in real-time, and started from pendulum_demo.
At first, we found reported stddev was wrong because of the following issue.
https://github.com/ros2/realtime_support/issues/94
At the time, we created #450. (It was almost half year ago!)

You kindly gave us the advice, but we have had no time to work on it. Thank you very much.

**Comment by clalancette** [comment]
@y-okumura-isp Thanks, I had totally forgotten about that!  I'm going to go ahead and close that issue now, thanks!

**Pull request merged**
