### PR TITLE
add missing runtime dependencies

### PR DESCRIPTION
**Pull request by mikaelarguedas**

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
ready for review

**Comment by Karsten1987** [comment]
lgtm. I guess there are problems when packaging ?

**Comment by mikaelarguedas** [comment]
Packaging does pass but running fails because the launchfile is trying to spawn these nodes while they don't exist (because not installed if we don't declare these deps)

**Comment by mikaelarguedas** [comment]
I'll take https://github.com/ros2/demos/pull/153#issuecomment-313472084 as an approval and will go ahead and merge this

**Pull request merged**
