### PR TITLE
Prevent pendulum_control demos from using typesupport introspection

### PR DESCRIPTION
**Pull request by dhood**
[This commit](https://github.com/ros2/rosidl/pull/158/commits/1e4b0741cbd82da5e62b0822ab24f293ede12ba4#diff-4845b4409f48ba8429ddbfdb2d93816fR8) caused pendulum_control tests to start failing for rmw implementations without typesupport introspection support e.g. http://ci.ros2.org/job/ci_linux/1615/testReport/(root)/projectroot/test_demo_pendulum_teleop__rmw_connext_cpp/

This fixes the failing `pendulum_control` tests for connext static (and opensplice). 

http://ci.ros2.org/job/ci_linux/1627/testReport/ (pendulum demos don't run on windows or os x)

(after approved I'll fix the commit history)

### CODE REVIEW

**Comment by dirk-thomas** [comment]
lgtm

**Comment by wjwwood** [comment]
lgtm too, make sure you squash on commit, it looks like you have a merge commit and possibly a duplicate commit in here.

**Comment by dhood** [comment]
have removed them now. won't squash since they're unrelated commits

**Comment by wjwwood** [comment]
sounds good

**Comment by mikaelarguedas** [comment]
you may want to add a comment explaining why the dependency order is not alphabetical. This would prevent someone to reintroduce the failure in a further "cleanup/linting" commit

**Comment by dhood** [comment]
that's a good point - will do that.

**Pull request merged**
