### PR TITLE
Adds copy constructor and assignment operator to ROSCvMatContainer

### PR DESCRIPTION
**Pull request by gonzodepedro**

### CODE REVIEW

**Comment by clalancette** [comment]
As context, we'll need this in place in order for https://github.com/ros2/rclcpp/pull/1849 to successfully compile and run.

**Review by audrow — APPROVED** [review]
Looks good to me.

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15824/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10502/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/13488/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16108/)

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
Two approvals, and CI is green, so going ahead and merging this one.

**Pull request merged**
