### PR TITLE
move wiki doc to pkg readme

### PR DESCRIPTION
**Pull request by Karsten1987**
move doc from ros2 wiki to pkg readme

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Please start each sentence on a new line (following the [developer guide](https://index.ros.org/doc/ros2/Developer-Guide/#markdown)).

**Comment by Karsten1987** [comment]
This is one-to-one copied from the ros2 wiki. I guess that's generated.
https://github.com/ros2/ros2_documentation/edit/master/Managed-Nodes.rst

Does that mean we should reiterate over all entries in the future? This
seems quite tedious.

**Comment by dirk-thomas** [comment]
> I guess that's generated.

No, someone wrote it just like that.

> This seems quite tedious.

Having followed the guideline in the first place would have avoided having to update it :wink:

**Comment by sloretz** [comment]
> This seems quite tedious.


`%s/\. /.\r/g`

**Comment by dirk-thomas** [comment]
> The lines should not have any trailing white spaces.

**Comment by Karsten1987** [comment]
> %s/\. /.\r/g

@sloretz I see you're a man of culture as well. I recommend `/gc` though as they are quite some false positives.

**Comment by Karsten1987** [comment]
side note: 
```
" clear trailing white
nnoremap <leader>clear :%s/\s\+$//<cr>:let @/=''<CR>
```

**Comment by tfoote** [comment]
There's one test failure here: http://build.ros2.org/job/Bpr__demos__ubuntu_bionic_amd64/4/ It looks like you might have found a flakey test ;-)

```
Test Result (1 failure / +1)
composition.test_api_srv_composition__rmw_fastrtps_cpp.xunit.missing_result
```

@ros-pull-request-builder retest this please.

**Pull request merged**
