### PR TITLE
Remove unnecessary dependency on ros2run

### PR DESCRIPTION
**Pull request by hidmic**
Precisely what the title says.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
In order to remove the dependency you must also remove its usage from here: https://github.com/ros2/demos/blob/bde11a9f7d2cd4504feb430920caec52a47dff56/pendulum_control/test/execute_with_delay.py#L19

**Comment by hidmic** [comment]
Argh, I had not seen that use. Brought back in https://github.com/ros2/demos/pull/413/commits/1665dbc170f4e58c8cd263e21e288608e4f33a53.

**Comment by hidmic** [comment]
Sanity CI for `lifecycle` and `dummy_robot_bringup`:
  * Linux [Build Status](http://ci.ros2.org/job/ci_linux/8607/)

**Comment by dirk-thomas** [comment]
I though the goal was to remove all dependencies on the `ros2cli` repo?

**Comment by hidmic** [comment]
> I though the goal was to remove all dependencies on the `ros2cli` repo?

We would have to get rid of the `ros_testing` -> `ros2test` -> `ros2cli` chain of dependencies, so it doesn't seem possible (unless we re-discuss that as well). Anyways, unnecessary dependencies can still go away.

**Pull request merged**
