### PR TITLE
Fix using-declaration

### PR DESCRIPTION
**Pull request by esteve**
This fixes a compile error caused by https://github.com/ros2/demos/pull/35

### CODE REVIEW

**Comment by esteve** [comment]
There's a pending error I'm working on, do not review yet.

**Comment by jacquelinekay** [comment]
HeapPoolMemoryStrategy is going away in the next PR, btw.

**Comment by esteve** [comment]
Remaining error fixed, ready for review.

**Comment by esteve** [comment]
I've built this locally and the error seems to be gone, I'll merge this PR.

**Pull request merged**
